### ISSUE TITLE
Old files remain even after originals have been removed

### ISSUE THREAD

**Issue by anfedorov** [AgentME/flow-copy-source#4]
Would be helpful to remove any `.flow` files that are no longer in the source.

**Comment by AgentME** [comment]
I think it could be useful, but when being used with babel it would be an incomplete solution because it wouldn't solve the issue of old .js files still being around too unless babel had the same option.

To avoid this issue, a project's prepare command could start with removing the output directory like [react-draggable-list's does](https://github.com/StreakYC/react-draggable-list/blob/master/package.json).
